mi_proyecto/blog/urls.py
# blog/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('', views.blog_home, name="home"),
    # Enlace de quienes_somos
    path('equipo/', views.quienes_somos, name="quienes_somos"),

]

mi_proyecto/inicio/urls.py
from django.urls import path
from . import views

app_name = 'inicio'

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('contacto/', views.contacto, name="contacto"),
    path('mejoras/', views.formulario_mejora, name="mejoras"),
    path('listado_contactos/', views.listado_contactos, name="listado_contactos"),
    path('listado_contactos/<int:contacto_id>/',
         views.detalle_contacto, name="detalle_contacto"),
]

mi_proyecto/mi_proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inicio.urls')),
    path('blog/', include('blog.urls')),
]

mi_proyecto/blog/models.py
from django.db import models


class Post(models.Model):
  # Atributos
    titulo = models.CharField(max_length=70, null=False)
    contenido = models.TextField()
    creado = models.DateTimeField(auto_now_add=True)

mi_proyecto/inicio/models.py
from django.db import models

# Create your models here.


class Contacto(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()
    mensaje = models.TextField()
    creado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre


class Mejora(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()
    sugerencia = models.TextField()
    prioridad = models.CharField(
        max_length=10,
        choices=[
            ('baja', 'Baja'),
            ('media', 'Media'),
            ('alta', 'Alta'),
        ]
    )
    creado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.nombre} - {self.prioridad}"

mi_proyecto/inicio/forms.py
from django import forms
from .models import Contacto, Mejora


class ContactoForm(forms.ModelForm):
    class Meta:
        model = Contacto
        fields = ['nombre', 'email', 'mensaje']


class MejoraForm(forms.ModelForm):
    class Meta:
        model = Mejora
        fields = ['nombre', 'email', 'sugerencia', 'prioridad']

mi_proyecto/blog/views.py
from django.shortcuts import render

# Create your views here.


def blog_home(request):
    return render(request, 'blog/home.html')


def quienes_somos(request):
    return render(request, "blog/quienes_somos.html")

mi_proyecto/inicio/views.py
from django.shortcuts import render, redirect
from .forms import ContactoForm, MejoraForm
from .models import Contacto

# Create your views here.


def inicio(request):
    return render(request, 'inicio/inicio.html')


# Formulario


def contacto(request):
    if request.method == 'POST':
        form = ContactoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('inicio:inicio')
    else:
        form = ContactoForm()

    return render(request, 'inicio/contacto.html', {'form': form})


def listado_contactos(request):
    buscar = request.GET.get('buscar', '')

    contactos = Contacto.objects.all().order_by('-creado')

    if buscar:
        contactos = (
            contactos.filter(nombre__icontains=buscar) |
            contactos.filter(email__icontains=buscar) |
            contactos.filter(mensaje__icontains=buscar)
        )

    return render(request, "inicio/listado_contactos.html", {
        "contactos": contactos,
        "buscar": buscar,
    })


def detalle_contacto(request, contacto_id):
    contacto = Contacto.objects.get(id=contacto_id)
    return render(request, "inicio/detalle_contacto.html", {
        "contacto": contacto,
    })

# Formulario de mejoras


def formulario_mejora(request):
    if request.method == 'POST':
        form = MejoraForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('inicio:inicio')
    else:
        form = MejoraForm()

    return render(request, 'inicio/mejoras.html', {'form': form})

mi_proyecto/blog/templates/blog/home.html
<!DOCTYPE html>
<html>
<head>
    <title>Mi Blog</title>
</head>
<body>
    <h1>Bienvenido a mi blog</h1>
    <p>Esta es la pantalla principal del blog.</p>

    <h2> Enlace </h2>
    <a href=" {% url 'quienes_somos' %} ">Texto del enlace</a>

</body>
</html>

mi_proyecto/blog/templates/blog/quienes_somos.html
<!DOCTYPE html>
<html>
<head>
    <title>Quiénes Somos</title>
</head>
<body>
    <h1>Quiénes Somos</h1>
    <p>Somos un pequeño equipo apasionado por compartir información y contenido de calidad en nuestro blog.</p>

    <p>Nuestro objetivo es aprender, enseñar y crear una comunidad donde todos podamos crecer juntos.</p>

    <h2> Enlace </h2>
    <a href=" {% url 'home' %} ">Texto del enlace</a>
</body>
</html>

mi_proyecto/inicio/templates/inicio/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Mi Proyecto{% endblock %}</title>
</head>
<body>
    <header>
        <h1>{% block titleH1 %}Mi Proyecto Django{% endblock %}</h1>
        <nav>
            <a href="{% url 'inicio:inicio' %}">Inicio</a> |
            <a href="{% url 'inicio:contacto' %}">Contacto</a> |
            <a href="{% url 'inicio:listado_contactos' %}">Listado de Contacto</a> |
            <a href="{% url 'inicio:mejoras' %}">Mejoras</a>
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <p>Derechos reservados &copy; 2025</p>
    </footer>
</body>
</html>

mi_proyecto/inicio/templates/inicio/contacto.html
{% extends "inicio/base.html" %}

{% block title %}Contacto{% endblock %}

{% block titleH1 %}Contacto{% endblock %}

{% block content %}
<h2>Contacto</h2>
<p>Puedes enviarnos un correo a <strong>contacto@midominio.com</strong>.</p>
<form action="" method="post">
    {% csrf_token %}

    {{ form.as_div }}

    {% comment %} 
    
    <label>Nombre:</label>
    {{ form.nombre }}

    <label>Email:</label>
    {{ form.email }}

    <label>Mensaje:</label>
    {{ form.mensaje }}

    <button type="submit">Enviar</button> 
    
    {% endcomment %}

    <button type="submit"> Enviar Contacto</button>

</form>
{% endblock %}

mi_proyecto/inicio/templates/inicio/detalle_contacto.html
{% extends "inicio/base.html" %}

{% block content %}
<h2>Detalle del contacto</h2>

<p><strong>Nombre:</strong> {{ contacto.nombre }}</p>
<p><strong>Email:</strong> {{ contacto.email }}</p>
<p><strong>Mensaje:</strong><br>{{ contacto.mensaje }}</p>
<p><strong>Fecha:</strong> {{ contacto.creado }}</p>

<a href="{% url 'inicio:listado_contactos' %}">Volver</a>
{% endblock %}

mi_proyecto/inicio/templates/inicio/inicio.html
{% extends "inicio/base.html" %}

{% block title %}Inicio{% endblock %}\

{% block titleH1 %}Inicio{% endblock %}

{% block content %}
<h2>Bienvenido a la página de inicio</h2>
<p>Esta es la pantalla principal del proyecto.</p>
{% endblock %}

mi_proyecto/inicio/templates/inicio/listado_contactos.html
{% extends "inicio/base.html" %}

{% block title %}Listado de Contactos{% endblock %}

{% block titleH1 %}Listado de Constactos{% endblock %}

{% block content %}
<h2>Listado de Contacto</h2>

<form method="get" style="margin-bottom: 20px;">
    <input type="text" name="buscar" placeholder="Buscar por nombre o email" value="{{ buscar }}">
    <button type="submit">Buscar</button>


<table border="1" cellpadding="10" cellspacing="0">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Email</th>
            <th>Mensaje</th>
            <th>URL</th>
        </tr>
    </thead>
    <tbody>
        {% for contacto in contactos %}
        <tr>
            <td>{{ contacto.nombre }}</td>
            <td>{{ contacto.email }}</td>
            <td>{{ contacto.mensaje }}</td>
            <td><a href={% url 'inicio:detalle_contacto' contacto.id %}>Enlace</a></td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="4">No se encontraron contactos.</td>
        </tr>
        {% endfor %}
    </tbody>


{% endblock %}

mi_proyecto/inicio/templates/inicio/mejoras.html
{% extends "inicio/base.html" %}

{% block title %}Mejoras{% endblock %}

{% block titleH1 %}Mejoras{% endblock %}

{% block content %}
<h2>Mejoras</h2>
<p>Puedes enviarnos un correo a <strong>contacto@midominio.com</strong>.</p>
<form action="" method="post">
    {% csrf_token %}

    {{ form.as_div }}

    <button type="submit"> Enviar Mejora</button>

</form>
{% endblock %}